apiVersion: v1
kind: Secret
metadata:
  name: hello-app-tls
  namespace: dev
type: kubernetes.io/tls
data:
  tls.crt: |
        -----BEGIN CERTIFICATE-----
        ## update your crt content here
        -----END CERTIFICATE-----
  tls.key: |
        -----BEGIN RSA PRIVATE KEY-----
        ## updated your Key here
        -----END RSA PRIVATE KEY-----