apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress1
spec:
  rules:
    - host: mynginx
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-ingress1
                port:
                  number: 80
  tls:
    - hosts:
        - mynginx
      secretName: nginx-tls-secret
