apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "files/tls.crt" | b64enc | quote }}
  tls.key: {{ .Files.Get "files/tls.key" | b64enc | quote }}
