# nginx/values.yaml
replicaCount: 1

service:
  type: NodePort
  port: 80
  nodePort: 30080

ingress:
  enabled: false

tls:
  enabled: false
  selfSigned: true
  secretName: ""

https:
  enabled: false
  tlsPort: 443
  redirectToHttps: false
