replicaCount: 1

service:
  type: NodePort
  port: 80
  nodePort: 30080

image:
  repository: nginx
  tag: 1.21.1
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Enable HTTPS redirection
  hostname: Banupriyas-Air


tls:
  enabled: true
  selfSigned: true
  secretName: nginx-tls-secret
  crt: |-
    -----BEGIN CERTIFICATE-----
    {{ .Files.Get "tls.crt" | indent 8 }}
    -----END CERTIFICATE-----
  key: |-
    -----BEGIN PRIVATE KEY-----
    {{ .Files.Get "tls.key" | indent 8 }}
    -----END PRIVATE KEY-----

https:
  enabled: false
  tlsPort: 443
  redirectToHttps: false
