replicaCount: 1

service:
  type: NodePort
  port: 80
  nodePort: 30080

image:
  repository: nginx
  tag: 1.21.1
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Enable HTTPS redirection
  hostname: demo.rajkumar.home


tls:
  enabled: true
  selfSigned: true


https:
  enabled: true
  tlsPort: 443
  redirectToHttps: true
