replicaCount: 1

service:
  type: NodePort
  port: 80
  nodePort: 30080

image:
  repository: nginx
  tag: 1.21.1
  pullPolicy: IfNotPresent

ingress:
  enabled: false

tls:
  enabled: false
  selfSigned: true
  secretName: ""

https:
  enabled: false
  tlsPort: 443
  redirectToHttps: false
